### ISSUE TITLE
Outdated `pino` peer dependency

### ISSUE THREAD

**Issue by bryandrenner** [FormidableLabs/pino-lambda#26]
# Expected

I can use `pino-lambda` with the latest version of Pino.

# Actual

Installing the latest version of Pino alongside `pino-lambda` results in NPM errors like:

```
npm WARN Could not resolve dependency:
npm WARN peer pino@"^6.0.0" from pino-lambda@3.0.0
npm WARN node_modules/pino-lambda
npm WARN   pino-lambda@"^3.0.0" from the root project
```

# Implementation

`pino-lambda` has a peer dependency on `pino@^6.0.0`, whereas the latest `pino` version is `7.x`.

**Comment by flofehrenbacher-sz** [comment]
Would you consider to change it to `>=6.0.0` instead of `^6.0.0`?
